### ISSUE TITLE
"minecraft:lore" and "minecraft:repairable" don't work

### ISSUE THREAD

**Issue by lumagatto** [boyonk913/item-components#9] opened 2024-11-21 20:47 UTC
```
{
	"targets": [
		"minecraft:netherite_boots",
		"minecraft:netherite_chestplate",
		"minecraft:netherite_helmet",
		"minecraft:netherite_leggings",
		"minecraft:diamond_boots",
		"minecraft:diamond_chestplate",
		"minecraft:diamond_helmet",
		"minecraft:diamond_leggings",
		"minecraft:iron_boots",
		"minecraft:iron_chestplate",
		"minecraft:iron_helmet",
		"minecraft:iron_leggings",
		"minecraft:chainmail_boots",
		"minecraft:chainmail_chestplate",
		"minecraft:chainmail_helmet",
		"minecraft:chainmail_leggings",
		"minecraft:gold_boots",
		"minecraft:gold_chestplate",
		"minecraft:gold_helmet",
		"minecraft:gold_leggings",
		"minecraft:leather_boots",
		"minecraft:leather_chestplate",
		"minecraft:leather_helmet",
		"minecraft:leather_leggings",
		"minecraft:turtle_helmet"
	],
	"components": {
	  "minecraft:lore": [
		{
			"text":""
		},
		{
			"text":"Will this fit you?",
			"color":"gray",
			"italic":true
		}
	  ]
	}
  }
  
```
```
{
  "targets": "minecraft:trident",
  "components": {
    "minecraft:attribute_modifiers": [
	  {
	    "type": "minecraft:attack_speed",
		"id": "minecraft:base_attack_speed",
		"amount": -2,
		"operation": "add_value",
		"slot": "mainhand"
	  },
	  {
	    "type": "minecraft:attack_damage",
		"id": "lgs:base_attack_damage",
		"amount": 7,
		"operation": "add_value",
		"slot": "mainhand"
	  },
	  {
	    "type": "minecraft:entity_interaction_range",
		"id": "lgs:base_entity_interaction_range",
		"amount": 1,
		"operation": "add_value",
		"slot": "mainhand"
	  }
	],
	"minecraft:repairable": {
		"items": "minecraft:nautilus_shell"
	}
  }
}
```
```
[21:46:48] [Server thread/ERROR]: Couldn't read components lgs:armor from lgs:item_components/armor.json in data pack srl_dp/LG-Survival_5.0
com.google.gson.JsonSyntaxException: Not a string: {"text":"Will this fit you?","color":"gray","italic":true}; Not a string: {"text":""} missed input: {"minecraft:lore":[{"text":""},{"text":"Will this fit you?","color":"gray","italic":true}]}
	at knot/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
	at knot/com.boyonk.itemcomponents.ItemComponentsManager.loadIntoMap(ItemComponentsManager.java:102) ~[item-components-1.1+1.21.2.jar:?]
	at knot/com.boyonk.itemcomponents.ItemComponentsManager.method_14491(ItemComponentsManager.java:65) ~[item-components-1.1+1.21.2.jar:?]
	at knot/net.minecraft.class_4013.method_29490(class_4013.java:16) ~[server-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at knot/net.minecraft.class_4014.method_18365(class_4014.java:68) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:889) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:180) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:871) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:865) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18857(class_1255.java:147) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:829) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29439(MinecraftServer.java:1530) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3097.method_29480(class_3097.java:22) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3097.method_13530(class_3097.java:53) ~[server-intermediary.jar:?]
	at knot/com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
	at knot/net.minecraft.class_8865.method_54416(class_8865.java:29) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8865.execute(class_8865.java:13) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8856.method_54405(class_8856.java:8) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8847.method_54388(class_8847.java:8) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8854.method_54390(class_8854.java:107) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2170.method_54313(class_2170.java:384) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2170.method_9249(class_2170.java:314) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3244.method_58590(class_3244.java:1347) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3244.method_44356(class_3244.java:1335) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:889) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:180) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:871) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:865) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:123) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:833) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:719) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[21:46:48] [Server thread/ERROR]: Couldn't read components lgs:trident from lgs:item_components/trident.json in data pack srl_dp/LG-Survival_5.0
com.google.gson.JsonSyntaxException: Not a json array: "minecraft:nautilus_shell" missed input: {"minecraft:repairable":{"items":"minecraft:nautilus_shell"}}
	at knot/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
	at knot/com.boyonk.itemcomponents.ItemComponentsManager.loadIntoMap(ItemComponentsManager.java:102) ~[item-components-1.1+1.21.2.jar:?]
	at knot/com.boyonk.itemcomponents.ItemComponentsManager.method_14491(ItemComponentsManager.java:65) ~[item-components-1.1+1.21.2.jar:?]
	at knot/net.minecraft.class_4013.method_29490(class_4013.java:16) ~[server-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at knot/net.minecraft.class_4014.method_18365(class_4014.java:68) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:889) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:180) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:871) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:865) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18857(class_1255.java:147) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:829) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29439(MinecraftServer.java:1530) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3097.method_29480(class_3097.java:22) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3097.method_13530(class_3097.java:53) ~[server-intermediary.jar:?]
	at knot/com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
	at knot/net.minecraft.class_8865.method_54416(class_8865.java:29) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8865.execute(class_8865.java:13) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8856.method_54405(class_8856.java:8) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8847.method_54388(class_8847.java:8) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8854.method_54390(class_8854.java:107) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2170.method_54313(class_2170.java:384) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2170.method_9249(class_2170.java:314) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3244.method_58590(class_3244.java:1347) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3244.method_44356(class_3244.java:1335) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:889) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:180) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:871) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:865) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:123) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:833) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:719) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by boyonk913** [comment] 2024-11-28 14:11
Duplicate of #6

**Closed by boyonk913** 2024-11-28 14:11 UTC
